#!/bin/sh

# addtty - Invokes socat to add a tty.
# Usage: addtty [kill] [N]

if [ $USER != "root" ]; then
        echo "Warning! To add a tty user must be root!"
        exit 1
fi
if [ -z "$1" ]; then
	echo "No tty specified, using default (tty1)..."
	socat -d -d pty,rawer,echo=0,link=/dev/tty1 pty,rawer,echo=0,link=/dev/tty1 2>/dev/null || echo "Warning! Socat error! (Has it exited?)"; exit 1
else
	if [ "$1" = "kill" ]; then
		kill $(ps | grep -Fw "socat" | cut -d" " -f1) 2>/dev/null
		kill $(ps | grep -Fw "socat" | cut -d" " -f2) 2>/dev/null
		exit
	fi
	socat -d -d pty,rawer,echo=0,link=/dev/tty${1} pty,rawer,echo=0,link=/dev/tty${1} 2>/dev/null || echo "Warning! Socat error! (Has it exited?)"; exit 1
fi
